[tool.poetry]
name = "discord-app-example"
version = "0.1.0"
description = ""
authors = ["thijsfranck <thijsfranck@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
discord-py = {extras = ["voice"], version = "^2.4.0"}
python-dotenv = "^1.0.1"

[tool.poetry.dev-dependencies]
pre-commit = "^3.7.1"
pytest = "^8.2.2"
ruff = "^0.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
