name: Build

on:
  push:
    branches:
      - master
    paths:
      - .devcontainer/**

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build devcontainer image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/thijsfranck/discord-app-example-devcontainer
          cacheFrom: ghcr.io/thijsfranck/discord-app-example-devcontainer
          push: always
