name: Publish

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: read
  packages: write

timeout-minutes: 10

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python, Poetry and Dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.12
          poetry-version: 1.8.3

      - name: Build the Application
        run: poetry build

      - name: Build Docker Image
        run: docker build . -t ghcr.io/thijsfranck/discord-app-example:${{ github.ref }}

      - name: Publish Docker Image
        run: docker push ghcr.io/thijsfranck/discord-app-example:${{ github.ref }}
