name: Publish

on:
  push:
    tags:
      - v*.*.*

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      POETRY_VIRTUALENVS_CREATE: "false"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python, Poetry and Dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.12
          poetry-version: 1.8.3

      - name: Build the Application
        run: poetry build -f wheel
        shell: bash

      - name: Build and Publish the Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/thijsfranck/discord-app-example:${{ github.ref_name }},ghcr.io/thijsfranck/discord-app-example:latest

      - name: Setup Git User
        uses: fregante/setup-git-user@v2.0.1

      - name: Publish Documentation
        run: poetry run mike deploy -b public-docs --push --update-aliases ${{ github.ref_name }} latest
        shell: bash
