name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POETRY_VIRTUALENVS_CREATE: "false"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python, Poetry and Dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.12
          poetry-version: 1.8.3

      - name: Run Type Checking
        uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.370
          python-version: 3.12

      - name: Run Tests
        run: poetry run pytest
